name: group_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-417.0.dev <4.0.0'

dependencies:
  animations: ^2.0.7
  simple_animations: ^5.0.0+3
  flutter:
    sdk: flutter
  flutter_vector_icons: ^1.0.0
  flutter_easyloading: ^3.0.5
  http: ^0.13.5
  intl: ^0.18.0
  json_annotation: ^4.8.0
  number_text_input_formatter: ^1.0.0+1
  shared_preferences: ^2.1.2
  email_validator: ^2.1.17
  google_fonts: ^4.0.4
  flutter_secure_storage: ^8.0.0
  table_calendar: ^3.0.9
  syncfusion_flutter_charts: ^22.1.39

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/images/prize/
  uses-material-design: true
